
# General Configuration
unstable_features = true
max_width = 80
error_on_line_overflow = true
newline_style = "Unix"

# Operators
binop_separator = "Front"

# Whitespace
blank_lines_upper_bound = 1

# Code Layout
brace_style = "SameLineWhere"
combine_control_expr = true
empty_item_single_line = true
fn_single_line = true
format_strings = true
inline_attribute_width = 80
space_before_colon = false
space_after_colon = false
type_punctuation_density = "Wide"

# Comments
comment_width = 80
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true

# Macros
format_macro_matchers = true
format_macro_bodies = true
