# Options intended to be common for all developers.

wasm-size-limit: 4.5 MiB

required-versions:
  node: =16.15.0
  wasm-pack: ^0.10.2
#  TODO [mwu]: Script can install `flatc` later on (if `conda` is present), so this is not required. However it should
#              be required, if `conda` is missing.
#  flatc: =1.12.0
