[workspace]

members = [
    "lib/rust/ast",
    "lib/rust/launcher-shims",
    "lib/rust/lexer/definition",
    "lib/rust/lexer/generation",
    "lib/rust/parser",
    "lib/rust/parser-jni",
]

# These patch versions exist to allow local development of these libraries alongside Enso. It
# assumes you have `rust-lib` in the same directory as `enso`. See:
# https://github.com/enso-org/rust-lib/blob/main/docs/CONTRIBUTING.md#developing-in-conjunction-with-enso--ide
[patch.crates-io]
#enso-automata       = { path = '../rust-lib/src/automata'       }
#enso-data           = { path = '../rust-lib/src/data'           }
#enso-flexer         = { path = '../rust-lib/src/flexer'         }
#enso-generics       = { path = '../rust-lib/src/generics'       }
#enso-lazy-reader    = { path = '../rust-lib/src/lazy-reader'    }
#enso-logger         = { path = '../rust-lib/src/logger'         }
#enso-macro-utils    = { path = '../rust-lib/src/macro-utils'    }
#enso-optics         = { path = '../rust-lib/src/optics'         }
#enso-prelude        = { path = '../rust-lib/src/prelude'        }
#enso-shapely        = { path = '../rust-lib/src/shapely/impl'   }
#enso-shapely-macros = { path = '../rust-lib/src/shapely/macros' }

[profile.dev]
opt-level        = 0
lto              = false
debug            = true
debug-assertions = true

[profile.release]
opt-level        = 3
lto              = true
debug            = false
debug-assertions = false

[profile.bench]
opt-level        = 3
lto              = true
debug            = false
debug-assertions = false

[profile.test]
opt-level        = 0
lto              = false
debug            = true
debug-assertions = true
