[workspace]
resolver = "2"
# Listing only the "root" crates of each app/library. All path dependencies are included in the workspace automatically.
# If you want to add sub crate (like `app/gui/config` or `lib/rust/ensogl/example`), just add it as a path dependency
# where plausible.
members = [
  "app/gui",
  "app/gui/enso-profiler-enso-data",
  "build/cli",
  "build/macros",
  "build/enso-formatter",
  "build/intellij-run-config-gen",
  "build/deprecated/rust-scripts",
  "lib/rust/*",
  "lib/rust/parser/src/syntax/tree/visitor",
  "lib/rust/parser/jni",
  "lib/rust/parser/generate-java",
  "lib/rust/parser/debug",
  "lib/rust/profiler/data",
  "lib/rust/profiler/demo-data",
  "integration-test",
  "tools/language-server/logstat",
  "tools/language-server/wstest",
]
# The default memebers are those we want to check and test by default.
default-members = ["app/gui", "lib/rust/*"]

# We are using a version with extended functionality. The changes have been PR'd upstream:
# https://github.com/rustwasm/console_error_panic_hook/pull/24
# Remove this patch when the issue is resolved.
[patch.crates-io]
console_error_panic_hook = { git = 'https://github.com/enso-org/console_error_panic_hook' }

[profile.dev]
opt-level = 0
lto = false
debug = 0
debug-assertions = true

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
incremental = true
debug = false
debug-assertions = false

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.test]
opt-level = 0
lto = false
debug = true
debug-assertions = true

[profile.integration-test]
inherits = "test"
opt-level = 2

[profile.buildscript]
inherits = "dev"
opt-level = 1
lto = false
debug = true
debug-assertions = true

[workspace.dependencies]
tokio = { version = "=1.20.1", features = ["full", "tracing"] }
console-subscriber = "=0.1.7"
nix = "=0.24.1" # DO NOT BUMP UNTIL NIGHTLY IS UPDATED. Otherwise, it brings too new libc.
