[workspace]

members = [
    "lib/rust/enso-data",
    "lib/rust/enso-generics",
    "lib/rust/enso-logger",
    "lib/rust/enso-macro-utils",
    "lib/rust/enso-optics",
    "lib/rust/enso-prelude",
    "lib/rust/enso-shapely/impl",
    "lib/rust/enso-shapely/macros",
    "lib/rust/flexer",
    "lib/rust/lexer/definition",
    "lib/rust/lexer/generation",
    "lib/rust/lexer/tests",
]

[profile.dev]
opt-level = 0
lto       = false
debug     = true

[profile.release]
opt-level = 3
lto       = true
debug     = false
panic     = 'abort'

[profile.bench]
opt-level = 3
lto       = true
debug     = false

[profile.test]
opt-level = 0
lto       = false
debug     = true
