[workspace]

# Listing only the "root" crates of each app/library. All path dependencies are included in the workspace automatically.
# If you want to add sub crate (like `app/gui/config` or `lib/rust/ensogl/example`), just add it as a path dependency
# where plausible.
members = [
    "app/gui",
    "build/rust-scripts",
    "lib/rust/*",
    "lib/rust/profiler/data",
    "lib/rust/not-used/*",
    "integration-test"
]

# This directory is not a crate
exclude = ["lib/rust/not-used"]

# The default memebers are those we want to check and test by default.
default-members = ["app/gui", "lib/rust/*"]

[profile.dev]
opt-level = 0
lto = false
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.test]
opt-level = 0
lto = false
debug = true
debug-assertions = true

[profile.integration-test]
inherits = "test"
opt-level = 2
