[package]
name = "ide-view"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast = { path = "../language/ast/impl" }
parser = { path = "../language/parser" }
enso-config = { path = "../config" }
enso-frp = { path = "../../../lib/rust/frp" }
enso-prelude = { path = "../../../lib/rust/prelude" }
enso-shapely = { path = "../../../lib/rust/shapely" }
engine-protocol = { path = "../controller/engine-protocol" }
ensogl = { path = "../../../lib/rust/ensogl" }
ensogl-component = { path = "../../../lib/rust/ensogl/component" }
ensogl-derive-theme = { path = "../../../lib/rust/ensogl/app/theme/derive" }
ensogl-gui-component = { path = "../../../lib/rust/ensogl/component/gui" }
ensogl-text = { path = "../../../lib/rust/ensogl/component/text" }
ensogl-text-msdf = { path = "../../../lib/rust/ensogl/component/text/src/font/msdf" }
ensogl-hardcoded-theme = { path = "../../../lib/rust/ensogl/app/theme/hardcoded" }
ide-view-component-browser = { path = "component-browser" }
ide-view-execution-environment-selector = { path = "execution-environment-selector" }
ide-view-documentation = { path = "documentation" }
ide-view-graph-editor = { path = "graph-editor" }
ide-view-project-view-top-bar = { path = "project-view-top-bar" }
span-tree = { path = "../language/span-tree" }
gloo-utils = { workspace = true }
js-sys = { workspace = true }
multi-map = { workspace = true }
nalgebra = { workspace = true }
ordered-float = { workspace = true }
serde_json = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
strum = { workspace = true }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-test = { workspace = true }
welcome-screen = { path = "welcome-screen" }

[dependencies.web-sys]
version = "0.3.4"
features = []
