[package]
name = "rust-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Enso Team <contact@enso.org>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enso-parser = { path = "../../../lib/rust/parser" }
wasm-bindgen = { workspace = true }
serde_json = { workspace = true }
console_error_panic_hook = { workspace = true }
