[build]
target-dir = "target/rust/"
rustflags = ["--cfg", "tokio_unstable"]

[target.wasm32-unknown-unknown]
rustflags = [
  # Increas the stack size from 1MB to 2MB. This is required to avoid running out of stack space
  # in debug builds. The error is reported as `RuntimeError: memory access out of bounds`.
  "-C",
  "link-args=-z stack-size=2097152",
]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:2097152"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--stack,2097152"]
