resolver: lts-14.7

packages:
  - .

# prettier-ignore
ghc-options:
  $locals:
    -O2
    -Wall
    -Wno-name-shadowing
    -fexcess-precision
    -fexpose-all-unfoldings
    -flate-dmd-anal
    -fmax-worker-args=1000
    -fsimpl-tick-factor=400
    -fspec-constr-keen
    -fspecialise-aggressively
    -fstatic-argument-transformation
    -funbox-strict-fields
    -threaded
    -fomit-interface-pragmas
