name: Publish Developer Docs

on:
  push:
    branches: 
      - master
    paths:
      - 'docs/**'
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'luna/luna.github.io'
        ref: 'sources'
        token: ${{ secrets.Enso_PAT }}
    - name: set identity email
      run: git config --global user.email "actions@github.com"
    - name: set identity name
      run: git config --global user.name "GitHub Actions"
    - name: Checkout submodules
      run: git submodule update --init 
    - name: Update submodules
      id: status
      run: |
        git submodule update --init 
        git submodule update --remote --merge
        if [ -n "$(git status --porcelain)" ]; then
          echo "::set-output name=has_changes::1"
        fi
    - name: Push changes
      run: |
        git add .
        git commit -m "Update submodules"
        git push origin sources
      if: steps.status.outputs.has_changes == '1'
