name: Docs CI

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: ["*"]

env:
  nodeVersion: 12.18.0

jobs:
  check:
    name: Docs Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Library Sources
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}
      - name: Install Prettier
        run: npm install
      - name: Check Docs
        run: npx prettier --check .
