name: Enso Language Support for VSCode, IGV, NetBeans

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    paths:
      - "tools/enso4igv/**/*"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ["8"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Find out pom & micro versions
        working-directory: tools/enso4igv
        run: |
          # Why do we subtract a number? Read versioning policy!
          # https://github.com/enso-org/enso/pull/7861#discussion_r1333133490
          echo "POM_VERSION=`mvn -q -DforceStdout help:evaluate -Dexpression=project.version | cut -f1 -d -`" >> "$GITHUB_ENV"
          echo "MICRO_VERSION=`expr $GITHUB_RUN_NUMBER - 2100`" >> "$GITHUB_ENV"

      - name: Update project version
        working-directory: tools/enso4igv
        run: |
          echo "Setting version to $POM_VERSION.$MICRO_VERSION"
          mvn versions:set -DnewVersion="$POM_VERSION.$MICRO_VERSION"

      - name: Build with Maven
        run: mvn -B -Pvsix package --file tools/enso4igv/pom.xml
      - name: Archive NBM file
        uses: actions/upload-artifact@v3
        with:
          name: Enso IGV Plugin
          path: tools/enso4igv/target/*.nbm

      - name: Install Node.js modules
        run: mvn -B -Pvsix npm:install --file tools/enso4igv/pom.xml

      - name: Update package.json version
        run: mvn -B -Pvsix npm:exec@version --file tools/enso4igv/pom.xml

      - name: Build VSCode Extension
        run: mvn -B -Pvsix npm:run@vsix --file tools/enso4igv/pom.xml

      - name: Archive VSCode extension
        uses: actions/upload-artifact@v3
        with:
          name: VSCode Extension
          path: tools/enso4igv/*.vsix
