name: Nightly Release
on:
  schedule:
    - cron: 0 5 * * 2-6
  workflow_dispatch: {}
jobs:
  promote-nightly:
    name: Promote nightly
    uses: ./.github/workflows/promote.yml
    with:
      designator: nightly
    secrets: inherit
env:
  ENSO_BUILD_SKIP_VERSION_CHECK: "true"
